# Generated by Django 3.2.8 on 2021-10-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ano_veiculo',
            field=models.CharField(default=2015, max_length=200),
            preserve_default=False,
        ),
    ]
